2021-01-24 17:13:18,397 INFO    MainThread:7052 [wandb_setup.py:_flush():70] setting env: {}
2021-01-24 17:13:18,397 INFO    MainThread:7052 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-24 17:13:18,397 INFO    MainThread:7052 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-24 17:13:18,397 INFO    MainThread:7052 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-24 17:13:18,397 INFO    MainThread:7052 [wandb_init.py:_log_setup():318] Logging user logs to /home/iiitd/Desktop/Ahmad/cnn/wandb/run-20210124_171318-1iuj3rxr/logs/debug.log
2021-01-24 17:13:18,397 INFO    MainThread:7052 [wandb_init.py:_log_setup():319] Logging internal logs to /home/iiitd/Desktop/Ahmad/cnn/wandb/run-20210124_171318-1iuj3rxr/logs/debug-internal.log
2021-01-24 17:13:20,850 INFO    MainThread:7052 [wandb_run.py:_console_start():1308] atexit reg
2021-01-24 17:13:20,851 INFO    MainThread:7052 [wandb_run.py:_redirect():1175] redirect: SettingsConsole.REDIRECT
2021-01-24 17:13:20,851 INFO    MainThread:7052 [wandb_run.py:_redirect():1178] Redirecting console.
2021-01-24 17:13:20,851 INFO    MainThread:7052 [redirect.py:install():205] install start
2021-01-24 17:13:20,862 INFO    MainThread:7052 [redirect.py:install():220] install stop
2021-01-24 17:13:20,862 INFO    MainThread:7052 [redirect.py:install():205] install start
2021-01-24 17:13:20,866 INFO    MainThread:7052 [redirect.py:install():220] install stop
2021-01-24 17:13:20,866 INFO    MainThread:7052 [wandb_run.py:_redirect():1222] Redirects installed.
2021-01-24 17:13:20,867 INFO    MainThread:7052 [wandb_run.py:_atexit_cleanup():1278] got exitcode: 1
2021-01-24 17:13:20,867 INFO    MainThread:7052 [wandb_run.py:_restore():1250] restore
2021-01-24 17:13:20,867 INFO    MainThread:7052 [redirect.py:uninstall():224] uninstall start
2021-01-24 17:13:20,867 INFO    MainThread:7052 [redirect.py:_stop():279] _stop: stdout
2021-01-24 17:13:20,867 INFO    MainThread:7052 [redirect.py:_stop():285] _stop closed: stdout
2021-01-24 17:13:20,868 INFO    stdout    :7052 [redirect.py:_pipe_relay():121] relay done saw last write: stdout
2021-01-24 17:13:20,868 INFO    stdout    :7052 [redirect.py:_pipe_relay():137] relay done done: stdout
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:_stop():291] _stop joined: stdout
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:_stop():293] _stop rd closed: stdout
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:uninstall():228] uninstall done
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:uninstall():224] uninstall start
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:_stop():279] _stop: stderr
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:_stop():285] _stop closed: stderr
2021-01-24 17:13:20,868 INFO    stderr    :7052 [redirect.py:_pipe_relay():121] relay done saw last write: stderr
2021-01-24 17:13:20,868 INFO    stderr    :7052 [redirect.py:_pipe_relay():137] relay done done: stderr
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:_stop():291] _stop joined: stderr
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:_stop():293] _stop rd closed: stderr
2021-01-24 17:13:20,868 INFO    MainThread:7052 [redirect.py:uninstall():228] uninstall done
2021-01-24 17:13:21,472 INFO    MainThread:7052 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "52d7cdd7ff864e4182d3898f05bfa170"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 511
    }
  }
}

2021-01-24 17:13:23,478 INFO    MainThread:7052 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "6d4b4d8511034a67b138c9f33fdf19b6"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 4962
      total_bytes: 4962
    }
  }
}

2021-01-24 17:13:24,756 INFO    MainThread:7052 [wandb_run.py:_show_files():1614] logging synced files
2021-01-24 17:13:24,757 INFO    MainThread:7052 [internal.py:handle_exit():139] Internal process exited
